site: Jan Biernacki Personal Portfolio
url: 100xa.github.io
title: Jan Biernacki Personal Portfolio
description: I am a 21 year old Software Developer from Germany, mostly working with Flutter. Feel free to check out my projects!
    <a href="https://github.com/100xA" target="_blank" rel="noopener">@github</a>.
permalink: pretty

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
 

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
  blogs:
    output: true
    
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "/"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "/blog"
      type: "blogs"
    values:
      layout: "blog"    